# Generated by Django 4.2.7 on 2023-11-23 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('otchestvo', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('house', models.CharField(max_length=10)),
                ('korp', models.CharField(max_length=10)),
                ('apartments', models.IntegerField()),
                ('mob', models.CharField(max_length=25)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone_book.family')),
            ],
        ),
    ]
