# Generated by Django 4.2.7 on 2023-11-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='apartments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='house',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='korp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='otchestvo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='street',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
