# Generated by Django 4.2.7 on 2023-11-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0002_alter_record_apartments_alter_record_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='house',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='korp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='otchestvo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='record',
            name='street',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
