# Generated by Django 4.2.7 on 2023-11-25 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0006_alter_record_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Otchestvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phone_book.family'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_book.name'),
        ),
        migrations.AlterField(
            model_name='record',
            name='otchestvo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='phone_book.otchestvo'),
        ),
        migrations.AlterField(
            model_name='record',
            name='street',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='phone_book.street'),
        ),
    ]
