# Generated by Django 4.2.7 on 2023-11-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0007_name_otchestvo_street_alter_record_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='mob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_book.mob', unique=True),
        ),
    ]
