# Generated by Django 4.2.7 on 2023-11-25 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0009_alter_record_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='phone_book.family'),
        ),
        migrations.AlterField(
            model_name='record',
            name='mob',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='phone_book.mob'),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='phone_book.name'),
        ),
        migrations.AlterField(
            model_name='record',
            name='otchestvo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='phone_book.otchestvo'),
        ),
        migrations.AlterField(
            model_name='record',
            name='street',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='phone_book.street'),
        ),
    ]
