# Generated by Django 4.2.7 on 2023-11-25 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0010_alter_record_family_alter_record_mob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='mob',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='phone_book.mob'),
        ),
    ]
