# Generated by Django 4.2.7 on 2023-11-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0011_alter_record_mob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='mob',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='otchestvo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'ordering': ['id']},
        ),
    ]
